### ISSUE TITLE
Grid Scaling menu will not open in 0.8.6

### ISSUE THREAD

**Issue by DylanAngell** [UberV/scaleGrid#22]
Icon for the menu shows up in the left-hand menu bar, but clicking on it does nothing. Can't use any of the functions.

**Comment by Iron-E** [comment]
Also happening for me on 0.8.6

**Comment by LeJoker** [comment]
Same here on 0.8.6, using Firefox 89.0, Chrome 91.0.4472.77, and Chromium-based Edge 91.0.864.41

`Uncaught TypeError: canvas[control.layer] is undefined` is the error Firefox's console gives me, if that's helpful.

**Comment by prvsct** [comment]
Same here. I have already tried to reinstall the module. Menu simply won't open.

**Comment by VTTAssets** [comment]
I found that two issues are causing this behaviour:

1) Change the line https://github.com/UberV/scaleGrid/blob/0d25c13c4d4721a411edca1e1f6f7fdafe196025/gridScale.js#L46
 to `layer: "grid",`

2) **Update** The issue was acknowlegded to be one, so I am sure we will see an updated Foundry counterpart in due time. In the meantime, you can edit this one line of code below rather savely: `layer: this.activeLayer?.options.name,` to ` layer: this.activeLayer?.name,`

See https://gitlab.com/foundrynet/foundryvtt/-/issues/5395: Within `foundry.js` search for `class Canvas`, and change the following line within the `async tearDown()` function: 

```
    // Track current data which should be restored on draw
    this._reload = {
      scene: this.scene.id,
      layer: this.activeLayer?.options.name,
      controlledTokens: Object.keys(this.tokens._controlled),
      targetedTokens: Array.from(game.user.targets).map(t => t.id)
    };
```

to 

```
    // Track current data which should be restored on draw
    this._reload = {
      scene: this.scene.id,
      layer: this.activeLayer?.name,
      controlledTokens: Object.keys(this.tokens._controlled),
      targetedTokens: Array.from(game.user.targets).map(t => t.id)
    };
```

Monitor the Foundry issue for correctness, though, as I don't know much about working with layers. Without that change, the module works, but fails in the Canvas function, related to the GridLayer (which is not related to this module, but a core Foundry class). You will need to CTRL-R (reload) the game to continue working, this might be a better, though cumbersome method for people not wanting to change the source of the official Foundry (at least unless we received a comment on my reported issue on gitlab for it).

**Comment by DylanAngell** [comment]
Thanks so much for figuring this out and bringing the bug to the devs' attention, @VTTAssets . It looks like the Foundry-side bug was fixed in version 0.8.7, which just came out. 

> # The Game Canvas
> - Corrected an error occurring if the `GridLayer` is set as active and then the canvas is reloaded.

So the only thing that should need fixing now is the first issue, which is in Grid Scaler. I'll try to confirm once I get a chance to update my instance.

**Comment by Iron-E** [comment]
Should I make a PR @VTTAssets ?

**Comment by Iron-E** [comment]
I tested the fix and it worked for me. I set up a PR to implement the change discussed earlier; the commit gives credit to the source :+1:. Hopefully @UberV can get a chance to review it in the coming week or so :)

**Comment by UberV** [comment]
@Iron-E and @VTTAssets -- Thank you all for figuring this out!
